[package]
name = "llm-rs"
version = "0.1.0"
authors = ["Yijun Yu", "Vitali Borsak"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.9.0"
